### PR TITLE
Fix module.__init__() argument 1 must be string, not unicode (#310)

### LINKED ISSUE #310: module.__init__() argument 1 must be string, not unicode
**Description**

Module discovery does not accept unicode.

**Short reproducible**
```
$ pyblish --add-plugin-path "C:\Users\tje\Desktop"
Traceback (most recent call last):
  File "C:\Users\tje\Documents\conda-git-deployment\windows\miniconda\envs\tgbvfx-environment\Scripts\pyblish-script.py", line 11, in <module>
    load_entry_point('pyblish-base', 'console_scripts', 'pyblish')()
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\vendor\click\core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\vendor\click\core.py", line 474, in main
    self.invoke(ctx)
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\vendor\click\core.py", line 758, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\vendor\click\core.py", line 764, in invoke_subcommand
    Command.invoke(self, ctx)
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\vendor\click\core.py", line 659, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\vendor\click\core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\cli.py", line 222, in main
    available_plugins = api.discover(paths=plugin_paths)
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\plugin.py", line 1263, in discover
    module = types.ModuleType(mod_name)
TypeError: module.__init__() argument 1 must be string, not unicode
```

**Suggested solution**
Force unicodes to strings:
```python
module = types.ModuleType(str(mod_name))
```

### PR DESCRIPTION
**Pull request by tokejepsen**

### CODE REVIEW

**Comment by mottosso** [comment]
Thanks, this needs a test to first capture the problem.

**Comment by tokejepsen** [comment]
The failing checks seems to be due to ```unicode``` being renamed in python 3; https://stackoverflow.com/questions/19877306/nameerror-global-name-unicode-is-not-defined-in-python-3
How might we go about this?

**Comment by tokejepsen** [comment]
Due to lacking reproducibility, @mottosso do you think we should just close this?

**Comment by mottosso** [comment]
Sure, let's tackle it again once it resurfaces.

**Pull request closed without merging**
