### PR TITLE
GUI - First Step Of GUI - "just a Pyblish button"

### PR DESCRIPTION
**Pull request by madoodia**
Hey guys.
Sorry for delay in pushing this old work, but this is first step, and starting point of our works on GUI of Pyblish.
This is related to [GUI issue](#41), and i try to start title of GUI related issues with "GUI".
As you know we want to create Pyblish GUI with QML technology of QT framework, so for running this GUIs you need to these prerequistics :
- [Python 2.7](https://www.python.org/download/releases/2.7)
- [Qt 5.2 or later](http://qt-project.org/downloads)
- [PyQt 5.2 or later](http://www.riverbankcomputing.co.uk/software/pyqt/download5)

---
### First GUI

This is a really simple QML gui that i created for test.

first_gui

---
#### Workflow

Instead of clicking on a **publish** menu from **maya File menu** we should have a window that work for us.
Now in the First Step of work we just have a window with a simple button in it, that work for us like publish button inside maya,
I should say that this button does not work in maya yet. but when we hit the button it print a message for us, "**Your instances is published**".
Now we just should work with fake data, and in next steps we have more word to tell.

---
### Frontend folders

In frontend folder we have folders thatcontain all stuffs we need .

folders_01
- **content**: images we need for using in gui as icons
- **gui**: main code of our gui is in this folder such as main.py, pyblish.qml
- **utils**: all components (Types or Classes) that we create for reusing in our gui

---
### How work

when you install all needed frameworks you can test you qml running with this steps:
1. create a test.qml file contain:

```
import QtQuick 2.0
Rectangle {
    id: window
    width: 320
    height: 480
    color: "#00aa00"
}
```
1. in command prompt run:

`qmlscene.exe test.qml`
it works if you add `C:\Qt\Qt5.2.1\5.2.1\msvc2012_64\bin` to `PYTHONPATH`
and if works you can see a little green window.
1. now you can run : 
   `python main.py` from `pyblish/frontend/gui`

---
## Relationship between Python - PyQt - QML

There is a nice relationship between this three brothers to create a Strong GUI, 

```

  _________________________            _____________________
 |                         |          |                     |
 |         Python          <----------|        Pyblish      |
 |_________________________|          |_____________________|
              |                                  ^
  ____________v____________            __________|__________
 |                         |          |                     |
 |          PyQt           |          |       Maya          |
 |_________________________|          |_____________________|
         |          ^
  _______v__________|______
 |                         |
 |           QML           |
 |_________________________|
```

Now we don't have pyblish and maya connection in this version of GUI. and the role of pyblish is played with **Pyblish class** in **main.py** and the role of maya is played with **Host class**, that these two class create fake data for us now.

And Controller Class indeed is a new type that we should create for connecting to QML from PyQt.

Many things will be changed, but now this is start point of our work for GUI of Pyblish.

---
## How to get your pull request up and running?

I work in windows and so far i used cmd for working with github (but now i want to switch to sourceTree)

**cmd**:
1. create your fork from `https://github.com/abstractfactory/pyblish` here i have `madoodia`
2. git clone https://github.com/`madoodia`/pyblish
3. cd pyblish
4. git remote add abstractfactory https://github.com/abstractfactory/pyblish.git
5. git pull abstractfactory master
6. after you create your own changes: `git push origin master`
7. screenshot 194
8. create new issue

thanks.
and i wait for your comments.
good luck.

### CODE REVIEW

**Comment by mottosso** [comment]
Looks really good Mahmood, we've got a few topics to talk about already.
- Look/theme
- We have to compile PyQt5 to get it running with Python 2
- We then have to think about how this can be simplified for end-users
- We'll also have to figure out how to communicate between this standalone process and Maya

#### Compilation and end-users.

As PyQt5 isn't available for Python 2 via Riverbanks website, we'll have to compile it ourselves. However, our users shouldn't have to compile or install anything besides Pyblish, so we'll need to somehow streamline this process.

I've done some research about the licensing for PyQt5 and and it seems we're free to include a compiled version with our repo, like we are with nose and yaml etc. The only issue remaining then is including it for other platforms, but let's stick with Windows initially and worry about others later on.

**Comment by mottosso** [comment]
Another issue worth mentioning is the Travis build failure. This is due to Travis (the online service) isn't familiar with PyQt5. We'll need to find a good way to handle this, so that other tests can still run unimpeded.

Details here: https://travis-ci.org/abstractfactory/pyblish/builds/34625475

**Comment by madoodia** [comment]
### Look/Theme

we can work more on theme of gui, but for starting i select this them that we can change it before we go deeper into GUI creatin or after it.

### Compiling PyQt5
1. we can share PyQt5 that you build in repo
2. we can use this method for building ourselves
3. we can create an installer for installing all things we needed and after that create an executable standalone pyblish.

#### `2.` Building PyQt5 (i did it for myself in windows + visual studio)

**Prerequistics**:
- Visual Studio 2012
- Qt5.2.1
- Python 2.7 or later

**Installation**:
**Note**: Use VS2012 x64 Cross Tools Command Prompt as command prompt (Run as administrator)

`1.` **install SIP**:
- download latest version of SIP source code from http://www.riverbankcomputing.com/software/sip/download
- unzip it and take it to f:\ drive (or any drive as root)
- in VS2012 cmd : python configure.py
- in VS2012 cmd : nmake
- in VS2012 cmd : nmake install
  - (at the end of this steps sip.exe added to python folder and sip added to site-package)

`2.` **install PyQt5**:
- download latest version of PyQt5 source code from http://www.riverbankcomputing.com/software/pyqt/download5
- unzip it and take it to f:\ drive (or any drive as root)
- in VS2012 cmd : python configure.py
- in VS2012 cmd : nmake
- in VS2012 cmd : nmake install
  - (at the end of this steps PyQt5 folder added to site-package)

`3.` **add these to PATH env**:
- C:\Python27
- C:\Python27\Lib\site-packages\PyQt5 

### communicate between this standalone process and Maya
- I think we should use [ZeroMQ](http://zeromq.org/), but when and who work on it, i don't know, and now i should just work on fake data

**Comment by mottosso** [comment]
Thanks for that @madoodia. Just to clarify, my comments are directed to all of us, so we can all get going on a discussion, and not something I'm expecting you to have all the answers for right away. 

Great initiative on posting build instructions. One of the issues with building ourselves, is that we will all need a license of Visual Studio 2013, which is rather expensive. I'm not sure whether the (free) Express edition works but if it does that would remove that hassle.

**Comment by mottosso** [comment]
In the spirit of working with mock data, here's some helpful information.
- Full source code available [here](https://gist.github.com/mottosso/124d376c46853a574c0a)

### Mocking instances

An instance is a collection of data that is on its way to become one or more files on disk. The context contains one or more instances, and as plugins only deal with contexts, we'll need it to make an instance:

``` python
import pyblish.backend.plugin

context = pyblish.backend.plugin.Context()
instance = context.create_instance(name='MyInstance')
```

The next step is to add a family, so that compatible plugins can operate on it.

``` python
instance.set_data('family', value='my_family')
```

And that's it. We can now publish this instance.

``` python
for type in ('selectors', 'validators', 'extractors', 'conforms'):
    for plugin in pyblish.backend.plugin.discover(type):
        plugin().process(context)
```

This will take it through the stages of being published. But of course, we have no plugins compatible with the family `my_family`. So we'll need to make some.

### Mocking plugins

A plugin is a subclass of `Plugin` which has a subclass for each type of plugin. So let's start with that.

``` python
class ValidateMyInstance(pyblish.backend.plugin.Validator):
     family = ['my_family']
     host = ['maya']

     def process_instance(self, instance):
         assert instance.data('family') == 'my_family'
```

This plugin is now compatible with our instance. And as we're in the midst of mocking, let's not bother saving this out to a file. Instead, we'll use it directly.

``` python
for type in ('selectors', 'validators', 'extractors', 'conforms'):

    if type == 'validators':
        # Run our mocked up plugin once validators kick in
        ValidateMyInstance().process(context)

    for plugin in pyblish.backend.plugin.discover(type):
        plugin().process(context)
```

### Conclusion

And so the story goes. Now we can easily make instances on our own behalf, instead of having Selectors create them for us. We can create our own plugins on-the-fly, without bothering with paths or discovery.

With this in mind, we should be able to make a fully-featured UI. A UI that displays what instances we've created, and what plugins are about to be processing them.

### Nail on the head

Since publishing typically is associated with actually writing something to disk, as a final example, let's mock a plugin that does this.

``` python
instance.set_data('document_content', 'Hello World!')
instance.set_data('document_name', 'MyDocument.txt')
```

As you'll see, this isn't your typical Maya instance with nodes being exported. This is a plain file writer, storing a very important message on disk.

Now we need our extractor.

``` python
import os

class ExtractDocument(pyblish.backend.plugin.Extractor):
    families = ['my_family']
    hosts = ['*']

    def process_instance(self, instance):
        content = instance.data('document_content')
        name = instance.data('document_name')

        # Since we aren't in Maya or anything, let's use the Current
        # Working Directory as parent to our document.
        parent_dir = instance.context.data('cwd')

        # The current working directory is being added to the context by
        # one of the included selector plugins. Now let's write the
        # document to disk.
        path = os.path.join(parent_dir, name)
        with open(path, 'w') as f:
            print "Writing message to %s" % path
            f.write(content)
```

And that's it. This extractor will keep overwriting the same file over and over, each time it is run, and it will save the file right next to wherever you first launched the script from.

Full example [here](https://gist.github.com/mottosso/124d376c46853a574c0a).

**Comment by madoodia** [comment]
I'm here again
:)

## Second GUI

### Image

pyblish_gui_02

### Video

[Pyblish_GUI_02.mp4](https://dl.dropboxusercontent.com/u/70052012/Pyblish_GUI_02.mp4)

---

After talking with @mottosso and working on the GUI agin (with many delay) i come back with a nice GUI that i hope you like it.
I captured a video for you from it. this GUI uses Mocking dat that @mottosso created and it contain this classes in it:
- **Host**
  - Creating my instances in my context
- **Pyblish**
  - Emulate Real Pyblish for calling publish_all based-on:
  
  ``` python
  type in ('selectors', 'validators', 'extractors', 'conforms')
  ```
- **ValidateMyInstance**
  - Class for Validating my instances (according to its family)
- **ExtractDocument**
  - Class for Extracting my instances (according to its family)
- **MyInstance**
  - Base class for my list of instances (related to relationship between PyQt-QML)
- **Controller**
  - A new type for QML that we created for us

---

The **GUI** shows our instances of the context and its count and you can see them in a listView.every instance is a button that contain description about its instance. in next versions we try to create some stuffs to modify attributes from GUI.

### Note:

There was a little problem in ValidateMyInstance class that appeared when we want to add other families to it:

``` python
families = ['my_family', 'maya', 'nuke']
```

That it will be disappear when you comment this line

``` python
# assert instance.data('family') == 'my_family'
```

We are here for complete Pyblish.
Good luck!

**Comment by mottosso** [comment]
### Validation in the UI

> There was a little problem in ValidateMyInstance class that appeared when we want to add other families to it

Actually, the error you were getting was a Validator telling you that an instance was not valid. :) The UI will have to deal with this gracefully, telling the user which instance failed the validation and how to fix it.

### It works

Other than that, it looks like you've gotten Pyblish working as a standalone application, producing files on disk from data in Python. This is great! It means Pyblish works with mock data, as it should, and that it is usable when being run on its own, and not through a host. 

In the future, we'll find ways to make use of this. One example may be to "publish" a folder with images into a Quicktime video, running them through validation first, and ending with Conform, registering the event into a database.

### Design

About the design, you are straying quite far from your original sketches. If you have new ideas on how to layout the application, make new sketches first, either on paper like the previous ones or in Photoshop to make it look as close as possible to the real thing.

Then we can talk about how it looks, _before_ you get into coding it. That way, we can talk about many more designs in a shorter time, than you having to implement each design first. Hope that makes sense!

As an example, here is a suggestion for how to layout the UI.

mockup

Things to note.
1. Layout the GUI out on an actual desktop background makes it tangible, and easier to put into context with where it is going to be used. Maybe even better is to put Maya behind it.
2. I think we can afford to reduce the space each widget takes up, it makes it a little easier to breathe.

Alternatively, we could make even more room by skipping boxes around instances.

mockup2

Finally, these are just suggestions. Do try and post design suggestions as images first, before implementing them, so we can iterate quicker and easier. Also don't forget to push your changes to your repo often (baby steps) so that is is easier to merge everything once done.

**Comment by tokejepsen** [comment]
good start @madoodia! some notes:
- scroll bar for the information section, to indicate there is more to view
- liked the categorization of families in your original sketches.

ui

**Comment by mottosso** [comment]
Good one! 

Here's another one from me.

mockup3

**Comment by mottosso** [comment]
Now with a scrollbar!

mockup4

**Comment by madoodia** [comment]
Good Points.
Thanks for your attention.
Because many things does not defined yet, i had to implement first then tell you, but from now we first talk about mock-ups then implement them.

> In the future, we'll find ways to make use of this. One example may be to "publish" a folder with images into a Quicktime video, running them through validation first, and ending with Conform, registering the event into a database.

I could not understand this.

> About the design, you are straying quite far from your original sketches

Yes, there is a little difference, but there is no problem to back too the origin.
I try to creating my component for GUI.and we will implement them gradually.But i will create mock-up first,sure.

thanks again

**Comment by madoodia** [comment]
Ok
Now  we are in this Step: **Visualizing Instances in GUI**
Do you have any other idea that i should implement on the GUI for this step?
for example any icon to other window related to instances, or anything?
please let me know.

> edited

And another point is that i don't know how should we categorize the list!?
Based-on family or other things?
let me know!

**Comment by mottosso** [comment]
An icon is a good idea! We could have an icon for instances, and one for categories. Then, once we get into plugins, each type of plugin could have its own icon, like selectors, validators etc.

Could you mock up an icon in an image like this so we can see what it looks like?

**Comment by madoodia** [comment]
What do you think about this?

New-Mock-Up

Categorized by Family.

**Comment by mottosso** [comment]
Beautiful. :)
1. I like that you can quickly see whether or not an instance is to be validated, extracted or conformed, along with seeing which instances won't get extracted. This is very useful information.
2. I like the look! The colors are great, the layout and sizes of items are great.
3. I'm assuming the GUIDE is just for us, but I could imagine it being very helpful to bring up, perhaps via a hotkey, so that users can be reminded or taught what each color means. How about holding F1 brings this up? Letting go can hide it again.

Could you expand on this UI, and show us what the interior of an instance would look like? Like in your video, each instance displayed its data(). A mockup of how that would look would be really great.

Next up would be to include the plugins. I'd suggest making the window bigger, either to the height or width. The important part about the plugins is to see:
1. Which will get run, per instance
2. The order in which they will run.

**Comment by madoodia** [comment]
I'm glad you like it.
Yes each step is related to prev step in **selecting**, **validating**, **extracting** and **conforming**.
Yes **GUIDE:** is for us. but i want to create Tooltip for each part.
Each instance contain its attributes according to its family.
We can create content of each instance modifyable or just text. we can decide about it.
I will create more mock up tomorrow.
We can use any icon we want instead of **V**, **E** and **C** and many other icons for many works.
And about more room for GUI i have a surprise for you.you will see. ;)
thanks

**Comment by tokejepsen** [comment]
further exploration of @madoodia example;
Pre-Publish
prepublish

Post-Publish
postpublish

I dont think I have nailed the layout yet, but its the kind of information I would expect to have. Opening the failed validator/extractor would show the error message.
Also in the future there could a fix button on the failed validator, if an auto-fix exists.

**Comment by madoodia** [comment]
### New Mock-ups for today

We can have access to modifying the attributes of an instance and edit them as we want.
Look at this image:

pyblish_gui_contentofinstance_01

After that when we click on **Yellow** button we can see all plugins that we have in new roller window underneath main window. and all plugins can be categorized with related mission.
Look at this image:

pyblish_gui_submenu_vec_01

**All texts are temporary and fake**
Let me know what do you think.
Thanks

> Edit: Adding images to post - Marcus

**Comment by tokejepsen** [comment]
cool stuff @madoodia!
- if you hit Publish without going into the plugins (yellow arrow), how would you indicate to the user what went wrong and where?
- You seem to have plugin categories when you hit the yellow button. We currently don't have that feature. Personally I would just have a list of plugins, that you can enable/disable (with some that you can't disable, for necessary validators etc.)
- are the arrow button by the red plugins so you can see the error message?
- what are the comments section for on the plugins?
- "Peter: TurnTables" should probably be "TurnTables: Peter", as Peter is an instance of the TurnTables family.

**Comment by tokejepsen** [comment]
also this reminds me that we needs to implement a nice name property for all plugins, in preparation for the UI.

**Comment by mottosso** [comment]
> also this reminds me that we needs to implement a nice name property for all plugins, in preparation for the UI.

Good point!

**Comment by madoodia** [comment]
Thanks @tokejepsen 

> if you hit Publish without going into the plugins (yellow arrow), how would you indicate to the user what went wrong and where?

**V**, **E**, **C** is for that, when VEC is colored mean instance is ready for publish.if user  checked the publishable checkbox of an instance that does not have colored VEC it get a warning message about it and automaticaly SubWindow appears. (I think)

> You seem to have plugin categories when you hit the yellow button. We currently don't have that feature. Personally I would just have a list of plugins, that you can enable/disable (with some that you can't disable, for necessary validators etc.)

Well, we can have 3 yellow button for 3 type of our plugins.with click on every button SubWindow appears and show its related plugins.you should notice that all of this GUIs are rough.And we can Enable/Disable every plugin and it actually affect on publish.

> are the arrow button by the red plugins so you can see the error message?

I could not understand

> what are the comments section for on the plugins?

It is extra capability of Pyblish. :)

I think we should talk more about more important things, all of these things are changable.

**Comment by madoodia** [comment]
> also this reminds me that we needs to implement a nice name property for all plugins, in preparation for the UI.

We should define good names. but step-by-step.

**Comment by tokejepsen** [comment]
> v, E, C is for that, when VEC is colored mean instance is ready for publish.if user checked the publishable checkbox of an instance that does not have colored VEC it get a warning message about it and automaticaly SubWindow appears. (I think)

I would probably vouch for an approach where if one the VEC letters aren't present, means that the instance does not have any plugins to be run in this step (eg. no "E", means no extraction plugins are defined for that instance)
I would also go with a grey, green, red color scheme throughout;
grey - not run
green - run successfully
red - run, but failed

See this image for the comments on plugins categorization and error messages;
comments

**Comment by madoodia** [comment]
Dear @tokejepsen , let's talk first about first image.
content of inctances.
then we talk about Plugins SubWindow.OK?
look
i just want to show something
but if i should explain everything i put in GUI the image will be red.
i think we should talk about important things, and step-by step.
not about **Peter:TurnTable** is Wrong and **TurnTable:Peter** is right
you know?
first image was about Content of an instance
but you didn't talk about it
and then i put an image about plugins.
if we should have categorize in plugins?
seperate plugins?
access to different type of plugins?
all in one window?
every plugin provide what information and what capability?
every plugin need what buttons?
when we use plugins?
when we hit buttons?
i should know somthing, otherwise i just can copy Quality Guard icons here, and i can't explain their workflows.
make sense?

**Comment by mottosso** [comment]
> make sense?

Sorry Mahmood, but could you try asking one question at time? I can't make sense out of your last post.

**Comment by mottosso** [comment]
I think it's getting a little cramped.

I would suggest trying to keep the amount of information visible at any point in time as small as possible. The last thing I would want to see is a single screen with all information on it at once.

There are a few tactics we can employ to help us with this, like hovering.

**Hovering**

hovering

Also let's try and keep in mind exactly what information is relevant to a user looking to publish, if he's looking for a summary, let's provide him with that. But I think what is most important is to be able to focus on specific parts of what is being published and to give the user a feeling of control, as opposed to just telling him what is going to happen next.

Here is an example of how each portion can be given lots of space and room to breathe.

dragging

> edit: typo

**Comment by tokejepsen** [comment]
I like the hovering idea to minimize information. Would say though that a clear indication about any failures is important.

> Here is an example of how each portion can be given lots of space and room to breathe.

I like the pop-out of additional information when selecting, which is similar to @madoodia idea of the yellow button but more streamlined. I can't though think of a use-case the example you are using of swithcing the order of the plugins?

How would you present information to the user like errors on plugins?

**Comment by mottosso** [comment]
> I can't though think of a use-case the example you are using of swithcing the order of the plugins?

Actually, neither can I. :) It was more an example of not packing too much information into each visible pixel on screen.

> How would you present information to the user like errors on plugins?

That would probably be difficult. How about keeping instances and plugins in the same canvas, and have sort of an Attribute Editor for details about things? That's where we could put things like documentation about what went wrong and a potential Repair button.

**Comment by tokejepsen** [comment]
> That would probably be difficult. How about keeping instances and plugins in the same canvas, and have sort of an Attribute Editor for details about things? That's where we could put things like documentation about what went wrong and a potential Repair button.

So you would toggle the instance open to see the plugins. Plugins would be indicated with some colour scheme to indicate Ready to Run/Run/Failed. Then selecting these plugins would open the Attribute Editor to see error messages, attributes editing, documentation and potential buttons?

**Comment by mottosso** [comment]
> So you would toggle the instance open to see the plugins. Plugins would be indicated with some colour scheme to indicate Ready to Run/Run/Failed. Then selecting these plugins would open the Attribute Editor to see error messages, attributes editing, documentation and potential buttons?

That sounds good, but does it look good? :)

**Comment by mottosso** [comment]
We could also try three canvases.

Instances -> Plugins -> Info

**Comment by tokejepsen** [comment]
> We could also try three canvases.

maybe.. I'm in favor of the two canvases; "Outliner" and "Attribute Editor". You select your instance and get information about that in the attribute editor. Toggling open the instance will get you the plugins, and selecting the plugins will get you information in the attribute editor.

**Comment by mottosso** [comment]
> I can't though think of a use-case the example you are using of swithcing the order of the plugins?

I just came to think of one.

When validation takes a few seconds and all of them succeeds but the last one, it can be helpful to rearrange the last one to process first. Especially in cases where validation takes a very long time and when the fix isn't obvious and the user has to test a few times.

It doesn't justify that particular UI, but reordering as a concept I think is helpful. If for no other reason than give the user a sense of control.

**Comment by ljkart** [comment]
Hi Folks, Seen many nice ideas shared by you guys which is truly wonderful.
Would like to share my point of view,

I like @madoodia design for displaying instances, but would like to say that the options in the GUI should be minimalistic and clean, Artist like to conquer the world by a click of a button!
But before looking into how the instances are listed would like to know how they are being created and configured?
Do every User create their Instances and set all the plugins for that at the time when they do publish, I don't think it is suitable, it will be an over burden for them.
So Most of the things has to be pre-configured like I mention in  [Configuration Setup for Pyblish](https://groups.google.com/forum/#!topic/pyblish/Sdd5hAQEE_g).

By saying that the instance view should be a GUI which help artist to identify how his asset/shot treated in the process of publish , what are all process is going to happen in the background and at last where he can find his end product.
1. Would like to share the first look of instance GUI which the artist may see.
   pyblishmaingui

Here I separated the attributes and plugins view from the main GUI. when the artist select an instance
where you can see options like,
&nbsp;1. View Attributes
&nbsp;2. View Plugins
&nbsp;3. Publish Status

Clicking Attribute button open up a new window where you can view, add and delete attributes for the instances. 

pyblishattrselected

Note: Those attributes whose delete buttons are disabled  which cannot be deleted.

Then if you click Plugins it will open up plugins gallery,

pyblishpluginselected

Here you can see all the plugins categories and available plugins.
You can have mandatory and optional plugins here, mandatory plugins are disabled and user doesn't have any access to it.
Note : Right now I am showing validators, will show others also soon after getting your feedback's.
Obviously will have doubt that @tokejepsen mentioned,

> if you hit Publish without going into the plugins (yellow arrow), how would you indicate to the user what went wrong and where?

That's is what I suggested we should pre-configure this settings as project setup and store somewhere when the artist load the GUI it loads up that settings (everything which are mandatory) so artist can publish without really checking all the plugins. and the following GUI will answer @tokejepsen second doubt.

Note : I would like to mock that project setup soon and will share with you.

Last for the least, this is an experimental,
How about showing all the process status which is happening at the background while publishing , that helps User to track the whole process and what went wrong where?.

pyblishprocessview

Note : by clicking on the status icon will show the error message if exists!, and even we can store the logs for all the process and can use this as history for future purposes.

Note: You have noticed that the search option, as you think it is for filtering instances.

Thoughts?

**Comment by mottosso** [comment]
> but would like to say that the options in the GUI should be minimalistic and clean, Artist like to conquer the world by a click of a button!

Hey @ljkart, thanks for this, it looks really good! I agree with this, publishing may happen several times a day and most times it won't be a matter of configuring but simply a matter of wanting to get your stuff out to the next artist.

> Do every User create their Instances and set all the plugins for that at the time when they do publish

Have a quick look at [the guide](http://pyblish.com/) for this, but in a nutshell, which instances are processed by which plugins is pre-configured from within each plugin itself. They are matched by compatible family, so users would never need to (or be able to) decide which plugins to use.

> So Most of the things has to be pre-configured like I mention in Configuration Setup for Pyblish.

This is certainly something we will be looking into, especially once we get our node editor, but I think it's safe to focus on the current interface. @ljkart try running the Publishing tutorial in [the guide](http://pyblish.com/) to get a feel for how this works.

> Here I separated the attributes and plugins view from the main GUI. when the artist select an instance where you can see options like,

I must admit I'm not particularly fond of the very small buttons on-top of a button that each perform a very important job.

To me, the most important information the UI must convey is in this order:
1. Which instances are being published.
2. Which plugins are being run on each instance.
3. Status messages about each plugin/instance, like what went right and what went wrong.

> Last for the least, this is an experimental,
> How about showing all the process status which is happening at the background while publishing , that helps User to track the whole process and what went wrong where?

This last mockup you posted is spot on, I think. I especially like the graphic at the top! That could possibly be a place to:
1. Select to filter plugins by their type; selection, extraction etc.
2. Display how many plugins exists for each step, like this:

progress1

When things go wrong, it is obvious where it happened and what to do.

progress2

**Comment by ljkart** [comment]
> which instances are processed by which plugins is pre-configured from within each plugin itself. They are matched by compatible family, so users would never need to (or be able to) decide which plugins to use.

So in this case what happen when an artist turned off a mandatory plugin and publish?
in that case we has to define a plugins that are optional and mandatory like we define the family.

> I must admit I'm not particularly fond of the very small buttons on-top of a button that each perform a very important job.

Sorry It was a mistake, Actually It  has to be something like the following, 

pyblishmaingui_v002

> 1.Which instances are being published.

can be easily seen from the current GUI by expanding instance type

> 2.Which plugins are being run on each instance.

easily seen from the sub-gui which popup when you click the "P" button.

> 3.Status messages about each plugin/instance, like what went right and what went wrong.

This can be addressed in the "Publish View" GUI when you hit publish.

I actually miss that part to show the success on each step like you mention by changing the color,
I really like the way you showed how many plugins exists for each step.Good point

One doubt- we don't want to stop validation if anything went wrong right? we have to complete the whole validation and show what went wrong and what is right?

**Comment by mottosso** [comment]
> can be easily seen from the current GUI by expanding instance type

Sorry, I should have been clearer.

What I mean is not that this information isn't in the picture, but that the three things I mentioned are of utmost importance and should be the most noticeable thing within the interface, everything else is secondary and in some cases completely optional.

As a guideline, think of this. If a user gets only a glance at the GUI and remembers only a single thing, what does he remember?

Let's dissect the last image.

order

At the moment, the most prominent thing is the search bar, as they take up the most space. Searching isn't necessarily a non-essential thing, it just isn't what matters most to users opening up the GUI for the first time.

Next, the categories. They take up a lot of space too, and yet they are also much less important than the instances themselves.

The circles. I actually prefer the way you had them in the previous mockup, as it looked like they appeared when the user hovered over it. This lessens the clutter and helps the user focus.

Now let's look at the other GUI.

order2

As though it were choreographed, my eyes starts by looking at the top of the page, working themselves down towards the end and, most importantly, each piece of information is important and augments the previous piece of information.

One last image.

order3

Here, no other information appears than that is necessary. Categories are faded, as they are of secondary importance. There is only instances and a button and no doubt about what to do next.

The graphics may not be the very best, but the information I think is enough.

Here is a mockup I've made for Pipi.

pipi_mockup_publisher_1

It has data at the top, instances to the left and validators to the right.

> One doubt- we don't want to stop validation if anything went wrong right? we have to complete the whole validation and show what went wrong and what is right?

That is right, validation keeps on going until the end. But subsequent plug-ins won't process until all validation succeeds.

**Comment by mottosso** [comment]
> So in this case what happen when an artist turned off a mandatory plugin and publish?
> in that case we has to define a plugins that are optional and mandatory like we define the family.

The GUI will govern how this will be implemented, but I always imagined it as just another property within each plugin.

``` python
import pyblish

class MyValidator(pyblish.Validator):
     optional = True
```

The GUI will then provide a checkbox for plug-ins that have this attribute, as in #92.

As the GUI is in full control over which instances to process using which plugins, its trivial to handle enabling/disabling of plug-ins from within the GUI code itself.

**Comment by ljkart** [comment]
> At the moment, the most prominent thing is the search bar, as they take up the most space. Searching isn't necessarily a non-essential thing, it just isn't what matters most to users opening up the GUI for the first time.

Imagine a huge set which has many instances and which had worked by an artist and given to another artist. Set contain many unnecessary instances and should not be published , in that case rather than scrolling down the GUI to find the proper instances he can easily search the instances to publish.
This is one scenario where I think search will be an option.

If you think search is taking more spaces then , GUI can be look like this also.
pyblishmaingui_v003

> The circles. I actually prefer the way you had them in the previous mockup, as it looked like they appeared when the user hovered over it. This lessens the clutter and helps the user focus.

Then what about showing only the publish status initially and others on hover! 
Note : frank is hovered here

pyblishmaingui_v003

I really like the way you designed Pipi GUI, especially the progress bar for validators and their descriptions and attribute view.

But Like I said if we think about large scene having many instances and their attributes, I wonder the space to occupy for each widget is enough or not? In that way it may look like the old 3ds Max GUI (sorry for 3dsMax lovers!), kind of messy and people dare to touch anything!

> but in a nutshell, which instances are processed by which plugins is pre-configured from within each plugin itself. They are matched by compatible family, so users would never need to (or be able to) decide which plugins to use.

Like you said then the artist are least bothered about what is being set in the publish GUI until and unless they are really want to change anything.
So the publish status will be more than enough the  artist to understand what are all going to be published and what is not, if they really want to change something they have the freedom to open the sub-GUI to edit. bearing that in mind I chose to separate the GUI.

> import pyblish
> class MyValidator(pyblish.Validator):
>      optional = True

exactly what I thought.

**Comment by mottosso** [comment]
I think the search bar looks fantastic down there, good job @ljkart 

@madoodia has got his hands full for the time being and might have trouble continuing on the GUI. @ljkart would you like to take over? As he was the only one familiar with QML, I would suggest we go easy and implement a first version with plain QtWidgets.

I'm working on getting [PyQt5 up on PyPI](https://github.com/pyqt/pyqt5). Installing it at the moment is complicated and involves compilation but by the time I'm finished we'll be able to have it automatically install upon installing Pyblish.

Let me know if you need any help getting set-up until then.

**Comment by mottosso** [comment]
Archiving this, but let's keep referencing this issue when we talk about visuals and GUI.

**Pull request closed without merging**
