### PR TITLE
Maya isolated, review plugin fixed, and plugins moving home

### PR DESCRIPTION
**Pull request by mottosso**
Speaks for themselves.

### CODE REVIEW

**Comment by mottosso** [comment]
Do have a look at [`userSetup.py`](https://github.com/mottosso/publish/blob/8da83230880f75322fd9b364ddbaccd895db9a8f/publish/integration/maya/userSetup.py) though, I had to run through some hacks to get the menu-item to show up properly, but I'm sure there is a better way.

**Comment by BigRoy** [comment]
Just wanted to let you know that cmds.evalDeferred could be replaced with maya's executeDeferred from maya.utils

``` python
import maya.utils

def createMenu():
   pass

maya.utils.executeDeferred(createMenu)
```

That way you wouldn't need to wrap up mel commands. Should work just a nicely. :)

**Comment by mottosso** [comment]
Thanks Roy, I did actually try that but couldn't manage to get the item to show still. I assumed it had to do with the order in which the two defers are executed, almost as if Python got executed before MEL, which would have caused Publish being added before the menu got built.

**Comment by BigRoy** [comment]
Hmm, makes sense! :) I've heard of _issues_ with executeDeferred before, but we use it all over the place in userSetup.py at the studio. But this sounds like it could be one of those 'issues' that I read about on the internet. As long as it works we're getting somewhere, can always optimize/fix later.

**Comment by mottosso** [comment]
Yeah, I would generally prefer it over evalDeferred too due to the benefit you spoke of above.

**Comment by tokejepsen** [comment]
works on my end:) had to make the integration folder into a module to update my userSetup.py in my setup with:

``` python
from publish.integration.maya import userSetup
userSetup.eval_append_to_filemenu()
```

**Comment by mottosso** [comment]
> works on my end:) had to make the integration folder into a module to update my userSetup.py in my setup

Ah, are you not having the `/integration/maya` folder on your PYTHONPATH? Are you instead adding that command to your `/Documents/maya/scripts/userSetup.py`?

That's something we should talk about too, in the [Installing](https://github.com/abstractfactory/publish/issues/31) issue, how to get from `pulling the repo` to `having Publish in your file-menu`. At the moment, I'm expecting users to append the `/integration/maya` folder to their PYTHONPATH, but that only applies to Maya. When Houdini gets an integration, it won't be making much use of `userSetup.py`

Another method would be to do what you've done here, to manually add it to your own `userSetup.py`. Ideally though I'd rather have it be fully automatic upon installing publish:

``` bash
$ pip install pypublish
$ # Done!
```

**Comment by tokejepsen** [comment]
think I missed out on the PYTHONPATH method, will be using that now:)

**Comment by mottosso** [comment]
Merging and documenting "domain.py" a little better in Wiki.
https://github.com/abstractfactory/publish/wiki/Quickstart#domainpy

**Pull request merged**
