### PR TITLE
Iterator now sorting the plugins before iteration

### PR DESCRIPTION
**Pull request by PaulSchweizer**
Also updated the respective test and added venv to gitignore

### CODE REVIEW

**Comment by tokejepsen** [comment]
Cool!

What does this solve? Is there an issue to reference to this?

**Comment by PaulSchweizer** [comment]
I came across this when using the `pyblish.util.integrate` function (as well as the functions for the other steps) and thought this should be fixed as it does not yield the same behaviour as the "regular" pyblish method where the plugins are pre-sorted.
Should I open a ticket? Or use things in a different way?

**Comment by tokejepsen** [comment]
The best way to would be make a test, so we can ensure functionality in the future as well.

**Comment by PaulSchweizer** [comment]
The test is are already in place, as mentioned above

**Comment by mottosso** [comment]
This affects a core mechanic of Pyblish, and thus makes me nervous. :S

Plug-ins are sorted [during discovery](https://github.com/pyblish/pyblish-base/blob/b3e215740a4224e1a04c7fd77c3fb0a497ec6fbf/pyblish/plugin.py#L1375), I can't figure out why they'd need to be sorted again afterwards?

Maybe if you could post a reprodible?

**Comment by PaulSchweizer** [comment]
Maybe I'm using it wrong, but I am providing a list of plugins to the collect, validate etc. functions https://github.com/pyblish/pyblish-base/blob/master/pyblish/util.py#L199 

That list might not be in order, in which case it is exectuted out of order (meaning in it's given order).

I am using these functions separately for two reasons:
- We have a standalone tool that only performs validation on a given set of selectable validators
- We have our own ui for the entire publish process and it has to use these functions as well.

I can of course sort the list of plugins beforehand myself, but thought it safer if the sorting is performed inside of pyblish to avoid this inconsistency.

Of yourse there is also the possibility that the mentioned functions are not meant to be used like I am using them.

In the tests I added the above mentioned case, providing a list of plugins in the wrong order: https://github.com/pyblish/pyblish-base/pull/358/files#diff-08aca4e83f1cbb3f29db48aa9abcae9eR65

If that is not sufficient I can draft up a lengthier example, just let me know

**Comment by mottosso** [comment]
> but I am providing a list of plugins to the collect, validate etc.

Ah, yes. You should be able to pass a list of your order. If you wanted it sorted, then you can sort it before handing it in. This is expected, as you may want to actually control that order.

**Comment by PaulSchweizer** [comment]
Ok I see, then this PR is void, thanks for clarifying!

**Pull request closed without merging**
