### PR TITLE
Initial solution proposal for fixing #306

### PR DESCRIPTION
**Pull request by tokejepsen**
#306

I need a bit of help on this :(

I've replicated the test from the issue, and two others, along with the solution. The tests pass here, but when I'm NukeStudio I still get the same problem with imports.

### CODE REVIEW

**Comment by mottosso** [comment]
Just so I'm on the same page about your problem.

You have two files of the same name, in different directories. You would like to register both directories, and read the plug-ins from each of them.

```python
from pyblish import api
api.register_plugin_path("c:/path/1")
api.register_plugin_path("c:/path/2")
```

But you can't give them different names.

**E.g.**

```
first_plugin/
  first_collect.py
second_plugin/
  second_collect.py
```

Why?

I think the reason I haven't been looking at this as a real problem is because I don't understand what the problem is in giving each of them unique names. If you could help me understand how this isn't about cosmetics of files on disk, and really does prevent you from accomplishing a particular task then it'd be easier for me to think about this critically.

**Comment by tokejepsen** [comment]
> I think the reason I haven't been looking at this as a real problem is because I don't understand what the problem is in giving each of them unique names. If you could help me understand how this isn't about cosmetics of files on disk, and really does prevent you from accomplishing a particular task then it'd be easier for me to think about this critically.

After working on this, writing the tests and solution, I am somehow doubtful the problem is with same named plugins.
The original problem came when working on the pyblish-bumpybox set of plugins, where I got the import issues (see the results of the test: https://github.com/pyblish/pyblish-base/issues/306#issuecomment-261562349). It is these import issues that are preventing me some continuing. I honestly don't understand enough of pyblish to know where the problem is.

**Comment by mottosso** [comment]
That error might be unrelated; it could have to do with the automatic reload feature of plug-ins.

Are you able to reproduce it now? If so, try adding all imports into the `process()` function.

**Comment by mottosso** [comment]
Or wait, sorry, you already did post the reproducible.

**Comment by tokejepsen** [comment]
> If so, try adding all imports into the process() function.

Adding all the external imports used in the process() function definitely works. So I could workaround the problem for now, but guessing we would want to resolve the issue instead.

> If you rename those modules, does the error still occur?

Renaming the modules in the reproducible works, which is why when I saw the same error in the pyblish-bumpybox plugins, I assumed it was the same issue. Though renaming the plugins in pyblish-bumpybox, more specific the Hiero/NukeStudio plugins, does not resolve the issue. Even tried other things like renaming the class and making the plugin exclusive to the "nukestudio" host.

**Comment by mottosso** [comment]
> Adding all the external imports used in the process() function definitely works. So I could workaround the problem for now, but guessing we would want to resolve the issue instead.

Yes, that would be good I think, but that is a different issue. Once we've made paths unique, this will still be a problem.

It's because as soon as a module is reloaded, the old one is garbage collected and so all references to the old module from a newly reloaded one will be invalid.

Modules get garbage collected once there is no more references to it, and the only reference to modules is in the `sys.modules` dictionary.

You can test this for yourself by importing a module of your choice, and removing it.

```python
import sys
import my_module
sys.modules.pop("my_module")

my_module.my_function()
# ERROR
```

Now because each plug-in is a class, and the class references things from the module-level, such as your module-level imports, the class will be trying to reach garbage collected global references. This is why you are seeing these issues, and the reason it is resolved by putting all of your imports into the `process()` function; in there they are loaded and used in the same place with no room for one being garbage collected.

> Though renaming the plugins in pyblish-bumpybox, more specific the Hiero/NukeStudio plugins, does not resolve the issue. Even tried other things like renaming the class and making the plugin exclusive to the "nukestudio" host.

Ok, we should resolve this non-unique naming problem. But this sounds like a different issue we should resolve first.

Are you able to reproduce the error when each of your plug-in files have unique names?

**Comment by tokejepsen** [comment]
> Are you able to reproduce the error when each of your plug-in files have unique names?

I checked and all the file names in pyblish-bumpybox are unique, so I'm drawing a blank for where the issue could be.

> Now because each plug-in is a class, and the class references things from the module-level, such as your module-level imports, the class will be trying to reach garbage collected global references. This is why you are seeing these issues, and the reason it is resolved by putting all of your imports into the process() function; in there they are loaded and used in the same place with no room for one being garbage collected.

Maybe we should store those references to the module level imports in sys.modules?

**Comment by mottosso** [comment]
> I checked and all the file names in pyblish-bumpybox are unique, so I'm drawing a blank for where the issue could be.

Could you help me reproduce this?

**Comment by tokejepsen** [comment]
Save this to ```check_unique_names.py```:
```python
import os


plugins = {}
for root, dirs, files in os.walk("."):
    for f in files:
        mod_name, ext = os.path.splitext(f)

        if not f.endswith(".py"):
            continue

        path = os.path.join(root, f)
        if f in plugins.keys():
            plugins[mod_name].append(path)
        else:
            plugins[mod_name] = [path]

for key, value in plugins.iteritems():
    if len(value) >= 2:
        print value
```
In terminal:
```
cd [pyblish-bumpybox repository]
python /path/to/check_unique_names.py
```

**Comment by tokejepsen** [comment]
This test shows the error I'm getting in NukeStudio, basically loosing the reference to the module imports:
```python
@with_setup(lib.setup_empty, lib.teardown)
def test_same_named_plugins():
    """Having same named plugins works"""

    with lib.tempdir() as temp:
        first_module = os.path.join(temp, "first_plugin", "collect.py")
        print("Writing temporarily to: %s" % first_module)
        pyblish.api.register_plugin_path(os.path.dirname(first_module))

        if not os.path.exists(os.path.dirname(first_module)):
            os.makedirs(os.path.dirname(first_module))

        with open(first_module, "w") as f:
            f.write("""
import os
import pyblish.api

class FirstCollect(pyblish.api.ContextPlugin):

    order = pyblish.api.CollectorOrder

    def process(self, context):
        self.log.info(os)
""")

        second_module = os.path.join(temp, "second_plugin", "collect.py")
        print("Writing temporarily to: %s" % second_module)
        pyblish.api.register_plugin_path(os.path.dirname(second_module))

        if not os.path.exists(os.path.dirname(second_module)):
            os.makedirs(os.path.dirname(second_module))

        with open(second_module, "w") as f:
            f.write("""
import pyblish.api

class SecondCollect(pyblish.api.ContextPlugin):

    order = pyblish.api.CollectorOrder

    def process(self, context):
        pass
""")

        context = pyblish.util.publish()

        log_message = None
        for result in context.data["results"]:
            if result["records"]:
                log_message = result["records"][0].message

        assert log_message == str(os)
```

**Comment by mottosso** [comment]
Isn't that using identical names?

I mean, can you help me reproduce a situation where the files have unique names and still throw an error?

**Comment by tokejepsen** [comment]
> I mean, can you help me reproduce a situation where the files have unique names and still throw an error?

Sorry no, it seems to only be in NukeStudio, and I can't reproduce outside cause I have no idea about where the problem is.

**Comment by tokejepsen** [comment]
Although it throws the same error as the repoducible, so its loosing the reference to the imported modules.

**Comment by mottosso** [comment]
Ok. Does the solution in this PR address the issue?

**Comment by tokejepsen** [comment]
No, it does not resolve the issue unfortunately. Going to close this and resort to having import statements in the class.

**Comment by mottosso** [comment]
Ok, for completeness and when we return to this topic, there are two separate but similar issues at play here.

1. The files within which plug-ins reside must have unique names, because their names are used as identifiers in `sys.modules["plugin_file_here"]` and any identical name loaded after another would overwrite the first one.
2. Automatic reload breaks module-level references.

The reason this PR didn't resolve (2) was because the similarities of names wasn't the issue, automatic reload was.

Solving that would involve looking at the `discover()` function and either (1) disable automatic reload or (2) somehow "merging" the differences between a newly loaded module and the one loaded before it. At the moment, it's doing a plain overwrite, without regards to what was there before, and it's possible we could take inspiration from Git and try to establish (1) which attributes and methods on each contained plug-in class changed and integrate these changes more delicately.

The problem there is that if we do it not-so-elegantly, we run into the risk of obscure run-time errors, the kind that goes away when you "restart Maya".

There are other plug-in frameworks out there for Python, it's possible they have thought about this harder and come up with a solution. But what most of them do, including Maya's plug-in mechanism, is simply not do automatic reload. That would simplify things greatly.

**Pull request closed without merging**
