### PR TITLE
First prototyping (wip) for modular design based on Actions.

### PR DESCRIPTION
**Pull request by BigRoy**
- Separate base classes into core.py
- Remove redundant code from maya.py for this design.
- Add examples for Selectors, Validators, Extractors.
- NOTE: There's no working prototype/code at this point (consider WIP)

### CODE REVIEW

**Comment by mottosso** [comment]
Excellent, having a look now!

**Comment by BigRoy** [comment]
Something to note is that the _Actions_ are now directly interacting with the _Context_ in `Action.process()`. This allows the user to accidentally change the _Context_ somewhere the _Action_ should not. Instead the _Action_ should only be allowed access to its inputs/outputs. This way the _Action_ also doesn't need to know the parameters name on the _Context_ but only on itself, which is great because that's what the user is actually implementing.

Think of the inputs and outputs as _Attributes_ on a _Node_ where the Node is the Action. The Action doesn't have access to anything other than the inputs it requested. _To avoid confusion: The Action CAN access stuff in a Maya scene or something in a folder on you HDD, but the input of the Action will configure what objects it will look for or what the folder's path is._

Let me know if this doesn't make any sense.

**Comment by mottosso** [comment]
How do you feel about renaming "Action" -> "Filter" to align with [Pipes and Filters](http://msdn.microsoft.com/en-us/library/ff647419.aspx)?

**Comment by BigRoy** [comment]
Personally I think _Filter_ sounds confusing and _Action_ seems more accurate. I also thought about calling it _Node_ because that might be more familiar for people in our industry, especially if we go with a more _Node Graph_ style. And _Filter_ might be confusing with Selectors that 'filter' the provided _Context_. I'm currently also thinking about how the Artist perceives what something is and not necessarily the TD/Programmer that might recognize it from a data flow architecture.

Nevertheless I think I could also get used to _Filter_. Feel free to adapt it and lets see where that leads us?

**Comment by mottosso** [comment]
>  I'm currently also thinking about how the Artist perceives what something is and not necessarily the TD/Programmer that might recognize it from a data flow architecture.

Our domain language doesn't necessarily have to influence the user interface. I'm all for calling objects in a visual node graph "nodes" as opposed to "filters", like they are in Maya and Nuke et. al. Using "filter" in our code-base however would make for a quicker introduction to newcomers already familiar with the concept along with keeping our heads on the same page as we'd be looking at the same references for inspiration and understanding.

Additionally, "action" is already reserved terminology within the [Command Pattern](http://en.wikipedia.org/wiki/Command_pattern) which we may use within the GUI.

**Comment by BigRoy** [comment]
That's correct! 
Let's go with _Filter_!

Not sure about disconnecting between code and UI though, but we'll see when we get there!

> **Artist:** "Man... that Action here is giving me a hard time!"
> **TD:** "Oh yeah, let me update that Filter."
> _A little later._
> **Artist:** "These programmers are so weird!"
> **Artist2:** "Tell me about it."

**Pull request merged**
