### PR TITLE
Version 1.0.7

### PR DESCRIPTION
**Pull request by mottosso**
Hey guys,

This is a proposal for the next increment, 1.0.7. These are the changes since 1.0.6
- Improved logging of pyblish.main.publish()
- Refactored backend/frontend; frontends now in their own
  individual repositories.
- Added landscape.io code-quality badge

See [CHANGES](https://github.com/mottosso/pyblish/blob/c7740e23dfd13cde4e89d98f889a7f2c9d3d118e/CHANGES) for changes in other versions.
### Bye-bye `frontend` & `backend`

As Pyblish grows into becoming a more and more versatile tool, it has become clear to me that a single front-end is not going to be enough and that it's better to maintain separate repositories for each one; such as the [Web Frontend](https://github.com/abstractfactory/pyblish/issues/99), and [Main GUI](https://github.com/abstractfactory/pyblish/pull/72). I expect more front-ends to appear and I have lots in mind!

So, unless you have any objections, I've discarded these and returned to a simpler time. Here's a before and after.

``` python
# Before
import pyblish.backend.plugin
plugins = pyblish.backend.plugin.discover()

# After
import pyblish.plugin
plugins = pyblish.plugin.discover()
```
### Code quality

[Code Health](https://landscape.io/github/abstractfactory/pyblish/master)

I've also added another badge to our arsenal, this one will run a number of tests upon our code to ensure it lives up to various degrees of "code quality". It can be things like missing doc-strings in functions to non-PEP08 indentations or tabs instead of spaces etc.

https://landscape.io/github/abstractfactory/pyblish/3

At the time of this request, we're up at 98% which seems pretty good, although I have no experience with this particular service so it remains to be seen whether this number takes any skill to achieve or not.

### CODE REVIEW

**Comment by tokejepsen** [comment]
seems cool to me:)

**Comment by madoodia** [comment]
Very Nice.
I hope we can have a good starting GUI at incomming week.
Thanks

On Sat, Sep 27, 2014 at 8:07 PM, Toke Jepsen notifications@github.com
wrote:

> seems cool to me:)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abstractfactory/pyblish/pull/104#issuecomment-57058093
> .

## 

Bests,
madoodia

**Comment by mottosso** [comment]
> I hope we can have a good starting GUI at incomming week.

That would be swell. How are things on your end? Got any plans?

**Comment by madoodia** [comment]
Unfortunately we lost many times. (And this is my Fault) (i was busy)
But i’m more free from now and i will work on Main GUI
https://github.com/abstractfactory/pyblish/pull/72 in this week. and i
hope we can have a good starting point for Pyblish GUI soon.

:)
​:)
:ad

On Sat, Sep 27, 2014 at 8:14 PM, Marcus Ottosson notifications@github.com
wrote:

> I hope we can have a good starting GUI at incomming week.
> 
> That would be swell. How are things on your end? Got any plans?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abstractfactory/pyblish/pull/104#issuecomment-57058326
> .

## 

Bests,
madoodia

**Comment by mottosso** [comment]
Allright, that sounds good. Have a chat with @ljkart about it, he's also begun working on a minimal GUI.

And for the uninitiated, the GUI's are no longer hosted within this repo, but are instead being split into their own repositories, here:
- https://github.com/pyblish/pyblish-qml
- https://github.com/pyblish/pyblish-gui

You'll also note the alternative organisation "pyblish". I'm pondering whether it's a good idea to move our repos over to an independent organisation, considering the amount of extensions and integrations we're getting, so that it is a little easier to browse and find interesting repositories to use or contribute to. It'll essentially act like a group for everything Pyblish.

I'll be back in the next few days with more on this, however it won't affect anything in our workflow and history, likes and watches will all remain and this repo will re-direct automatically to the new home, making the transition practically invisible. I wouldn't be surprised if even pull-requesting or pulling would also be re-directed automatically.

**Comment by madoodia** [comment]
ok.
this is good organization.
i follow it.
good luck

On Sat, Sep 27, 2014 at 8:24 PM, Marcus Ottosson notifications@github.com
wrote:

> Allright, that sounds good. Have a chat with @ljkart
> https://github.com/ljkart about it, he's also begun working on a
> minimal GUI.
> 
> And for the uninitiated, the GUI's are no longer hosted within this repo,
> but are instead being split into their own repositories, here:
> - https://github.com/pyblish/pyblish-qml
> - https://github.com/pyblish/pyblish-gui
> 
> You'll also note the alternative organisation "pyblish". I'm pondering
> whether it's a good idea to move our repos over to an independent
> organisation, considering the amount of extensions and integrations we're
> getting, so that it is a little easier to browse and find interesting
> repositories to use or contribute to. It'll essentially act like a group
> for everything Pyblish.
> 
> I'll be back in the next few days with more on this, however it won't
> affect anything in our workflow and history, likes and watches will all
> remain and this repo will re-direct automatically to the new home, making
> the transition practically invisible. I wouldn't be surprised if even
> pull-requesting or pulling would also be re-directed automatically.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abstractfactory/pyblish/pull/104#issuecomment-57058621
> .

## 

Bests,
madoodia

**Pull request merged**
